#!/bin/bash
FRONTEND_PORT=${FRONTEND_PORT:-8000}
BACKEND_HOSTNAME=${BACKEND_HOSTNAME:-backend}
BACKEND_PORT=${BACKEND_PORT:-3000}

sed -i "s%FRONTEND_PORT%${FRONTEND_PORT}%;s%BACKEND_HOSTNAME%${BACKEND_HOSTNAME}%;s%BACKEND_PORT%${BACKEND_PORT}%" /etc/nginx/conf.d/default.conf
nginx -g "daemon off;"

