#!/bin/bash -x
NGINX_FRONTEND_PORT=${NGINX_FRONTEND_PORT:-8000}
NGINX_BACKEND_HOSTNAME=${NGINX_BACKEND_HOSTNAME:-backend}
NGINX_BACKEND_PORT=${NGINX_BACKEND_PORT:-3000}

sed -i -e "s/FRONTEND_PORT/${NGINX_FRONTEND_PORT}/" \
-e "s/BACKEND_HOSTNAME/${NGINX_BACKEND_HOSTNAME}/" \
-e "s/BACKEND_PORT/${NGINX_BACKEND_PORT}/" \
/etc/nginx/conf.d/default.conf

nginx -g "daemon off;"
